title: Li Xindie's Homepage
page-top-title: Li Xindie
top-section-bg-text: Computer Science
home-subtitle: Li Xindie&ensp;|&ensp;李心蝶
copyright-text: '&copy; Li Xindie 2023-2025. All Rights Reserved.'
